<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net480</TargetFramework>
		<PlatformTarget>x64</PlatformTarget>

		<RootNamespace>DWarsop</RootNamespace>
		<AssemblyName>DWarsop.QuickStart</AssemblyName>
		<OutputPath>D:/SteamLibrary/steamapps/common/RimWorld/Mods/DWarsop.QuickStart/1.5/Assemblies</OutputPath>
		<VersionPrefix>1.0.0.0</VersionPrefix>

		<DebugType>none</DebugType>

		<DebugSymbols>false</DebugSymbols>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<Compile Include="../Source/*" />

		<!-- Rimworld -->
		<Reference Include="D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Managed/Assembly-CSharp.dll">
			<Private>False</Private>
		</Reference>

		<!-- Unity Engine -->
		<Reference Include="D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Managed/UnityEngine.dll">
			<Private>False</Private>
		</Reference>
		<Reference Include="D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Managed/UnityEngine.CoreModule.dll">
			<Private>False</Private>
		</Reference>
		<Reference Include="D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Managed/UnityEngine.IMGUIModule.dll">
			<Private>False</Private>
		</Reference>
		<Reference Include="D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Managed/UnityEngine.TextRenderingModule.dll">
			<Private>False</Private>
		</Reference>
		<Reference Include="D:/SteamLibrary/steamapps/common/RimWorld/RimWorldWin64_Data/Managed/UnityEngine.InputLegacyModule.dll">
			<Private>False</Private>
		</Reference>
	</ItemGroup>
</Project>
